spring.application.name=Project-OpenSource

spring.datasource.url=jdbc:postgresql://ep-aged-art-at1lszy7.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FMk8bVtvjO3A
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

cloudinary.cloud-name=djhwgxagj
cloudinary.api-key=316733695532998
cloudinary.api-secret=Da6lKpxB_U0jImK62dkwwsQB-TA

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=VGhpcyBlcyB1bmEgY2xhdmUgc2VjcmV0YSBtdXkgbG9uZ2EgcGFyYSBzZWd1cmlkYWQgZGUgMTI4IGJpdHM=
jwt.expiration=86400000
